services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: app_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080