name: ci

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: unbutu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB.USERNAME}}         
          password: ${{secrets.DOCKERHUB.PASSWORD}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      -
        name: Build and push
        uses: docker/buil-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNMAE}}/clockbox:latest
